[package]
name = "RustDemo"
version = "0.1.0"
edition = "2021"
description = "A short description of my package"
license = "MIT/Apache-2.0"
repository = "https://github.com/akeboshi1/RustTest.git"

[dependencies]
wasm-bindgen = "0.2"
rand = "0.8.0"